In [1]:
doc_couples = [[1,2],[4,5]]
doc_emotions, doc_causes = zip(*doc_couples)
print(doc_emotions)
print(doc_causes)
print(type(doc_emotions))

(1, 4)
(2, 5)
<class 'tuple'>


In [2]:
print(list(map(lambda x: list(x), doc_couples)))
print(type(list(map(lambda x: list(x), doc_couples))))

[[1, 2], [4, 5]]
<class 'list'>


In [3]:
for i, x in enumerate([5,2]):
    print(i,x)

0 5
1 2


In [6]:
import numpy as np
import scipy.sparse as sp
N = 4
adj = np.ones((3, 3))
print(adj)
adj = sp.coo_matrix(adj)
print(adj.toarray())
adj = sp.coo_matrix((adj.data, (adj.row, adj.col)),
                    shape=(N, N), dtype=np.float32)
print(adj.toarray())

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [11]:
import numpy as np
a = np.zeros((3,3))
a[0,0]=1
a

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [71]:
import torch

In [72]:
x = torch.randn(2, 3, 3)

In [73]:
x

tensor([[[ 0.8026, -1.1382,  0.1685],
         [-0.9313, -0.7860, -1.6038],
         [-0.7109, -1.0787,  0.4627]],

        [[ 0.0999,  1.5957, -1.2468],
         [ 2.1629,  0.9061, -0.1792],
         [-2.0517, -1.5302,  0.6765]]])

In [74]:
y = torch.randn(2,3,3)
y

tensor([[[-0.8975,  2.2625,  0.5332],
         [ 0.5108,  0.3536, -0.2470],
         [ 0.6276,  0.0585, -0.9242]],

        [[-1.2524, -1.6832, -0.6013],
         [ 0.6443, -0.8099, -0.6748],
         [-0.3450, -0.7563,  2.4602]]])

In [75]:
x+y

tensor([[[-0.0950,  1.1243,  0.7016],
         [-0.4206, -0.4324, -1.8508],
         [-0.0833, -1.0202, -0.4615]],

        [[-1.1525, -0.0874, -1.8481],
         [ 2.8072,  0.0962, -0.8541],
         [-2.3966, -2.2865,  3.1366]]])

In [69]:
for b in x:
    for i in range(3):
        for j in range(3):
            print(type(b[i,j].item()))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>


In [58]:
a=torch.nonzero(x)
a.size()

torch.Size([18, 3])

In [48]:
a,b = torch.max(x, 3)

In [49]:
a

tensor([[[0.0356, 1.7977],
         [2.3587, 1.1097]]])

In [51]:
b.squeeze()

tensor([[0, 5],
        [4, 5]])

In [39]:
y = torch.diagonal(x, offset=0, dim1=1, dim2=2)

In [40]:
y

tensor([[[ 1.0322,  0.1935],
         [ 0.9036,  0.0605],
         [ 0.0490,  0.6073],
         [ 0.5269, -0.0679],
         [ 0.0983,  1.0625],
         [ 0.8690,  1.4900]]])

In [41]:
z = y.permute(0, 2, 1)

In [42]:
z.size()

torch.Size([1, 2, 6])

In [70]:
print("I is {}, U is {}.".format(1,2))

I is 1, U is 2.
